version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - SECRET_KEY=bee-tv-production-key
      - PORT=5000
      - HOST=0.0.0.0
      - DEBUG=False
    restart: always